In [7]:
from model_utils.encode_process_decode import LazyMLP
from model_utils.HyperEl import Model
import torch
device = torch.device('cuda')

In [8]:
n = Model(2)

print(n)

Model(
  (_output_normalizer): Normalizer()
  (_mesh_edge_normalizer): Normalizer()
  (_world_edge_normalizer): Normalizer()
  (learned_model): EncodeProcessDecode(
    (encoder): Encoder(
      (node_model): Sequential(
        (0): LazyMLP(
          (layers): Sequential(
            (linear_0): LazyLinear(in_features=0, out_features=128, bias=True)
            (relu_0): Sigmoid()
            (linear_1): LazyLinear(in_features=0, out_features=128, bias=True)
            (relu_1): Sigmoid()
            (linear_2): LazyLinear(in_features=0, out_features=128, bias=True)
          )
        )
        (1): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      )
      (mesh_edge_model): Sequential(
        (0): LazyMLP(
          (layers): Sequential(
            (linear_0): LazyLinear(in_features=0, out_features=128, bias=True)
            (relu_0): Sigmoid()
            (linear_1): LazyLinear(in_features=0, out_features=128, bias=True)
            (relu_1): Sigmoid()
            (l

c:\deeplearning\envs\gnn\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [5]:
from model_utils import normalization
from model_utils import Cloth

n = Cloth.Model(3)
# n = normalization.Normalizer(3,'n')
n.to('cpu')
print(n._mesh_edge_normalizer._acc_count)



tensor([0.])


In [3]:
d = {
    "a":1,
    "b":2
}
print(list(d.keys()))

['a', 'b']


In [1]:
import h5py

# 以只读模式打开HDF5文件
file = h5py.File('D:/project_summary/Graduation Project/tmp/datasets_hdf5/flag_simple/train/dataset.h5', 'r')


# 获取文件中的所有组
groups = list(file.keys())
print('Groups:', groups)
dataset = file['ex0']
# 获取文件中的所有数据集
print('Datasets:', type(dataset['world_pos']))

Groups: ['ex0', 'ex1', 'ex10', 'ex100', 'ex101', 'ex102', 'ex103', 'ex104', 'ex105', 'ex106', 'ex107', 'ex108', 'ex109', 'ex11', 'ex110', 'ex111', 'ex112', 'ex113', 'ex114', 'ex115', 'ex116', 'ex117', 'ex118', 'ex119', 'ex12', 'ex120', 'ex121', 'ex122', 'ex123', 'ex124', 'ex125', 'ex126', 'ex127', 'ex128', 'ex129', 'ex13', 'ex130', 'ex131', 'ex132', 'ex133', 'ex134', 'ex135', 'ex136', 'ex137', 'ex138', 'ex139', 'ex14', 'ex140', 'ex141', 'ex142', 'ex143', 'ex144', 'ex145', 'ex146', 'ex147', 'ex148', 'ex149', 'ex15', 'ex150', 'ex151', 'ex152', 'ex153', 'ex154', 'ex155', 'ex156', 'ex157', 'ex158', 'ex159', 'ex16', 'ex160', 'ex161', 'ex162', 'ex163', 'ex164', 'ex165', 'ex166', 'ex167', 'ex168', 'ex169', 'ex17', 'ex170', 'ex171', 'ex172', 'ex173', 'ex174', 'ex175', 'ex176', 'ex177', 'ex178', 'ex179', 'ex18', 'ex180', 'ex181', 'ex182', 'ex183', 'ex184', 'ex185', 'ex186', 'ex187', 'ex188', 'ex189', 'ex19', 'ex190', 'ex191', 'ex192', 'ex193', 'ex194', 'ex195', 'ex196', 'ex197', 'ex198', 'ex199

In [10]:
import torch

a = torch.Tensor([1,2])
b = torch.Tensor([2,3])
print(torch.concat((a,b),dim=0))

tensor([1., 2., 2., 3.])


In [11]:
a = [1,2,3]
print(a[:])

[1, 2, 3]


In [5]:
import torch

# 创建一个全False的矩阵
matrix_shape = (5, 5)  # 示例形状
matrix = torch.zeros(matrix_shape, dtype=torch.bool)

# 指定的行和列范围
i, j = 1, 3  # 行范围
n, m = 0, 2  # 列范围



# 设置指定列范围内的所有元素为 True
matrix[i:j+1, n:m+1] = True

# 交叉部分会被设置为 True 两次，但这不会影响结果
new_matrix = torch.zeros(matrix_shape, dtype=torch.bool)
print(matrix & new_matrix)



tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [7]:
def test(a,b):
    a = 1
    print(a,b)

a = 2
b= 2
print(a,b)
test(a,b)
print(a,b)

2 2
1 2
2 2


In [2]:
import torch
a = torch.Tensor([[2,3],[4,5]])
zero_size = torch.zeros(a.size(), dtype=torch.float32)
noise = torch.normal(zero_size, std=0.1)
print(noise)

tensor([[-0.0381, -0.0177],
        [-0.0497, -0.0789]])


In [12]:
import torch

# 创建一个示例 tensor
tensor = torch.tensor([[1], [2], [3], [4], [2], [5], [2]])

# 选出等于特定值（例如 2）的元素对应的序号
value = 2
indices = torch.nonzero(tensor.squeeze() == value).squeeze()

print(indices)
print(tensor[indices])
print(tensor)

tensor([1, 4, 6])
tensor([[2],
        [2],
        [2]])
tensor([[1],
        [2],
        [3],
        [4],
        [2],
        [5],
        [2]])


In [5]:
import torch


# 创建一个稀疏张量
indices = torch.tensor([[0, 0, 1, 1, 2, 2, 2],
[1, 1, 2, 2, 0, 0, 0]])
values = torch.tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.float32)
size = torch.Size([3, 3])

world_connection_matrix = torch.sparse_coo_tensor(indices, values, size)

# 打印原始稀疏张量
print("Original Sparse Tensor:")
print(world_connection_matrix)

# 使用 coalesce() 合并重复索引
coalesced_matrix = world_connection_matrix.coalesce()

# 获取合并后的索引
coalesced_indices = coalesced_matrix.indices()

print("\nCoalesced Indices:")
print(coalesced_indices)

Original Sparse Tensor:
tensor(indices=tensor([[0, 0, 1, 1, 2, 2, 2],
                       [1, 1, 2, 2, 0, 0, 0]]),
       values=tensor([1., 2., 3., 4., 5., 6., 7.]),
       size=(3, 3), nnz=7, layout=torch.sparse_coo)

Coalesced Indices:
tensor([[0, 1, 2],
        [1, 2, 0]])


In [3]:
import torch
indices = torch.tensor([[0, 0, 1, 1, 2, 2, 2],
[0, 1, 2, 2, 0, 0, 0]])
a = (indices[0] == indices[1]).nonzero(as_tuple=True)
print(a)

(tensor([0]),)
